services:
  sonar-postgre-db:
    image: postgres:alpine
    container_name: sonar-db
    restart: always 
    environment:
      POSTGRES_USER: sonaruser
      POSTGRES_PASSWORD: sonarPass@12345
      POSTGRES_DB: sonarqubedb
  sonarqube-server:
    image: sonarqube
    container_name: sonar-servercontainer
    depends_on:
      - sonar-postgre-db
    ports:
      - 9000:9000
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-postgre-db:5432/sonarqubedb
      SONAR_JDBC_USERNAME: sonaruser
      SONAR_JDBC_PASSWORD: sonarPass@12345
    restart: always
    