name: Docker Image CI
# name of pipeline 
# Now this  is github triggers 
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
# what kind of jobs we want to run 
jobs:
# name of job -- build is just name to refer we can have any name 
  cmd-test:
    # this runner provided by github it self we can ask for windows | linux | mac based runners 
    runs-on: ubuntu-latest 

    steps:
    - name: default action in github action official which check repo
    # uses section is desing to consume predefine actions 
    # to get list of workflow like checkout use this link https://github.com/actions
      uses: actions/checkout@v3
    - name: we can run commands depends on runs-on os 
      run: uname -r 

  post-test:
    runs-on: ubuntu-latest
    needs: cmd-test
    steps:
      - name: running commands
        run: |
          date
          cal
          whoami

      
   
